// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PRStatsStatus.
const (
	PRStatsStatusMERGED PRStatsStatus = "MERGED"
	PRStatsStatusOPEN   PRStatsStatus = "OPEN"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// Defines values for StatusStatStatus.
const (
	StatusStatStatusMERGED StatusStatStatus = "MERGED"
	StatusStatStatusOPEN   StatusStatStatus = "OPEN"
)

// Defines values for GetStatsSummaryParamsStatus.
const (
	MERGED GetStatsSummaryParamsStatus = "MERGED"
	OPEN   GetStatsSummaryParamsStatus = "OPEN"
)

// DeactivateResult defines model for DeactivateResult.
type DeactivateResult struct {
	DeactivatedUsers *int `json:"deactivated_users,omitempty"`
	Reassigned       *int `json:"reassigned,omitempty"`
	Removed          *int `json:"removed,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PRStat defines model for PRStat.
type PRStat struct {
	AssignCnt *int64  `json:"assign_cnt,omitempty"`
	PrId      *string `json:"pr_id,omitempty"`
}

// PRStats defines model for PRStats.
type PRStats struct {
	AuthorId      *string              `json:"author_id,omitempty"`
	CreatedAt     *time.Time           `json:"created_at"`
	MergedAt      *time.Time           `json:"merged_at"`
	PrId          *string              `json:"pr_id,omitempty"`
	PrName        *string              `json:"pr_name,omitempty"`
	Reassignments *[]ReassignmentEvent `json:"reassignments,omitempty"`
	Reviewers     *[]string            `json:"reviewers,omitempty"`
	Status        *PRStatsStatus       `json:"status,omitempty"`
	TransferCnt   *int64               `json:"transfer_cnt,omitempty"`
}

// PRStatsStatus defines model for PRStats.Status.
type PRStatsStatus string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// ReassignmentEvent defines model for ReassignmentEvent.
type ReassignmentEvent struct {
	ChangedAt     *time.Time `json:"changed_at,omitempty"`
	NewReviewerId *string    `json:"new_reviewer_id"`
	OldReviewerId *string    `json:"old_reviewer_id,omitempty"`
}

// ReviewerStats defines model for ReviewerStats.
type ReviewerStats struct {
	AssignCnt   *int64              `json:"assign_cnt,omitempty"`
	MergedPrCnt *int64              `json:"merged_pr_cnt,omitempty"`
	OpenPrCnt   *int64              `json:"open_pr_cnt,omitempty"`
	RecentPrs   *[]PullRequestShort `json:"recent_prs,omitempty"`
	UserId      *string             `json:"user_id,omitempty"`
}

// Stats defines model for Stats.
type Stats struct {
	ByPr     *[]PRStat     `json:"by_pr,omitempty"`
	ByStatus *[]StatusStat `json:"by_status,omitempty"`
	ByTeam   *[]TeamStat   `json:"by_team,omitempty"`
	ByUser   *[]UserStat   `json:"by_user,omitempty"`
}

// StatsSummary defines model for StatsSummary.
type StatsSummary struct {
	PrStatusCounts  *[]StatusStat `json:"pr_status_counts,omitempty"`
	TeamAssignments *[]TeamStat   `json:"team_assignments,omitempty"`
	TopReviewers    *[]UserStat   `json:"top_reviewers,omitempty"`
}

// StatusStat defines model for StatusStat.
type StatusStat struct {
	PrCount *int64            `json:"pr_count,omitempty"`
	Status  *StatusStatStatus `json:"status,omitempty"`
}

// StatusStatStatus defines model for StatusStat.Status.
type StatusStatStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamStat defines model for TeamStat.
type TeamStat struct {
	AssignCnt *int64  `json:"assign_cnt,omitempty"`
	TeamName  *string `json:"team_name,omitempty"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// UserStat defines model for UserStat.
type UserStat struct {
	AssignCnt *int64  `json:"assign_cnt,omitempty"`
	UserId    *string `json:"user_id,omitempty"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// GetStatsReviewerUserIdParams defines parameters for GetStatsReviewerUserId.
type GetStatsReviewerUserIdParams struct {
	// Limit Количество последних PR
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetStatsSummaryParams defines parameters for GetStatsSummary.
type GetStatsSummaryParams struct {
	// From Начало интервала (RFC3339)
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Конец интервала (RFC3339)
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Status Фильтр по статусу PR
	Status *GetStatsSummaryParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Топ-N ревьюверов (по умолчанию 10)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetStatsSummaryParamsStatus defines parameters for GetStatsSummary.
type GetStatsSummaryParamsStatus string

// PostTeamDeactivateJSONBody defines parameters for PostTeamDeactivate.
type PostTeamDeactivateJSONBody struct {
	TeamName string `json:"team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody PostTeamDeactivateJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(c *fiber.Ctx) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(c *fiber.Ctx) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(c *fiber.Ctx) error
	// Базовая агрегация по ревьюверу, PR, статусу и команде
	// (GET /stats)
	GetStats(c *fiber.Ctx) error
	// Статистика по конкретному PR
	// (GET /stats/pr/{pr_id})
	GetStatsPrPrId(c *fiber.Ctx, prId string) error
	// Персональная статистика ревьюера
	// (GET /stats/reviewer/{user_id})
	GetStatsReviewerUserId(c *fiber.Ctx, userId string, params GetStatsReviewerUserIdParams) error
	// Отфильтрованная статистика с топом ревьюверов
	// (GET /stats/summary)
	GetStatsSummary(c *fiber.Ctx, params GetStatsSummaryParams) error
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(c *fiber.Ctx) error
	// Деактивировать всех участников команды и переназначить/удалить ревьюеров
	// (POST /team/deactivate)
	PostTeamDeactivate(c *fiber.Ctx) error
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(c *fiber.Ctx, params GetTeamGetParams) error
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(c *fiber.Ctx, params GetUsersGetReviewParams) error
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(c *fiber.Ctx) error {

	return siw.Handler.PostPullRequestCreate(c)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(c *fiber.Ctx) error {

	return siw.Handler.PostPullRequestMerge(c)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(c *fiber.Ctx) error {

	return siw.Handler.PostPullRequestReassign(c)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(c *fiber.Ctx) error {

	return siw.Handler.GetStats(c)
}

// GetStatsPrPrId operation middleware
func (siw *ServerInterfaceWrapper) GetStatsPrPrId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "pr_id" -------------
	var prId string

	err = runtime.BindStyledParameterWithOptions("simple", "pr_id", c.Params("pr_id"), &prId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pr_id: %w", err).Error())
	}

	return siw.Handler.GetStatsPrPrId(c, prId)
}

// GetStatsReviewerUserId operation middleware
func (siw *ServerInterfaceWrapper) GetStatsReviewerUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Params("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsReviewerUserIdParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetStatsReviewerUserId(c, userId, params)
}

// GetStatsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetStatsSummary(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsSummaryParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", query, &params.From)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter from: %w", err).Error())
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", query, &params.To)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter to: %w", err).Error())
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", query, &params.Status)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter status: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetStatsSummary(c, params)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(c *fiber.Ctx) error {

	return siw.Handler.PostTeamAdd(c)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(c *fiber.Ctx) error {

	return siw.Handler.PostTeamDeactivate(c)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "team_name" -------------

	if paramValue := c.Query("team_name"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument team_name is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", query, &params.TeamName)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter team_name: %w", err).Error())
	}

	return siw.Handler.GetTeamGet(c, params)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument user_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", query, &params.UserId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	return siw.Handler.GetUsersGetReview(c, params)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(c *fiber.Ctx) error {

	return siw.Handler.PostUsersSetIsActive(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)

	router.Post(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)

	router.Post(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)

	router.Get(options.BaseURL+"/stats", wrapper.GetStats)

	router.Get(options.BaseURL+"/stats/pr/:pr_id", wrapper.GetStatsPrPrId)

	router.Get(options.BaseURL+"/stats/reviewer/:user_id", wrapper.GetStatsReviewerUserId)

	router.Get(options.BaseURL+"/stats/summary", wrapper.GetStatsSummary)

	router.Post(options.BaseURL+"/team/add", wrapper.PostTeamAdd)

	router.Post(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)

	router.Get(options.BaseURL+"/team/get", wrapper.GetTeamGet)

	router.Get(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)

	router.Post(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbbW8bx/H/Kov9/4HYAC1SlJ0ieqfYiqsXVlhKAYoKBHHiraRLyLvL3VGJIBCwxCRu",
	"KyOqgb4oDMSum34AmhYrWhKprzD7jYrdvefbOx5FSXb6xqDv9mFu9jczv50Z7eOG0TINneiOjRf3salY",
	"Sos4xOL/WydKa1VpkT+0ibXHHqjEblia6WiGjhcx/AojGMIZ9OCcPocRjGGAYAgX9BjBGYzhAnowghN6",
	"hAtYYzO+5QsVsK60CF7EDlFadf67gC3ybVuziIoXHatNCthu7JCWwjZ19kw22HYsTd/GnU4Bf2UTa0VN",
	"k+ofcAIDGNFDGNIfhHz0EMb0KYJLGHNRT2EMff54AOf0OEW8tk2suqZOJVzHe8kV+IgoDUfbVRxSJXa7",
	"6XAVW4ZJLEcjtpDdG6HW2X52aFFNd8g2sXCHCaDYtratMxHk71vGrvxlp+A9Mja/Jg2HDV+2LMOqEts0",
	"dJuwSeR7pWU2xU/2jv1oGCqbtfrlev2LL79afYQLuEVsW9lmTy1iG22rQZBuOGjLaOsq3yn6cf5S0cdi",
	"4X1M9HYLL27g9eWlJ/XlP66sra/hAq5UI7+fLFcfL7O9mRxLa2srj1fd/9YfLq0+Wnm0tL7svhVS1grx",
	"QwnJLUNTcLgbQrRgfC2hu9h48YU1iYor1TVHkRy4OMd6Q+fvtgyrxUax4/r0Pi5IjtbkGJRKnrKpLdm1",
	"7ewYKQsVcMMiHIBKVCZVccg9R+PmqbebTWWTIURYgETF1vaMS5ipApqWcBOyd55ptDwfpjmkxX/8v0W2",
	"8CL+v2Lg44qucRaroVnLu0Tn6nPXVixL2RNL72rkO9co/WUTEsSn2Y7itO0wwr+sLK/iAnaxLEOoYym6",
	"vUWs3MCQHn+72aySb9vETgUeUeuRr4r6TtfjIRhBD07Zv/QZ86Uwokf0R0SfwgD69Dn9GfowoE+ZF0V3",
	"SnNz5bvMheZWUC40Ls0MxllWMNvNZt0SukxFZXhMKj6nR0PMx8RFkW0c1qm/ZUF25rVs3KztGJYzrf/4",
	"X1CWTC9JJ5GMZTuKPsHvJT5SJ9/5B+KqayIejaYan5MjHlTdGWlRYdpY5Dp505pijmESfboZFmkQ3amb",
	"Vn53nkCwxOt4dC6f6lJUtrlXN638YgkSIBFmc68eYD3XWmt8eMZ6jE3nXo1R+4y1mK5yr8XouHytVMWu",
	"tVstRbD3qH5Ny9VLvWG0pwno2erhN42r8IQsPTmGWZdThOvVlvtZMl1xJeU0qyv51oRA6y7KoqK0SGtz",
	"GiWwVZ7wOamnlRIjYv4+fIX0hKiliO1umBBes+v8EhbebtMwmkTRs/2GeJdP0OAy6c8phHZOk/maLhET",
	"NJrY+iv7CorK2uRG1RgGQbZKfeObXaXThBP2SNO3DD5Yc1icx5Uq8sIzWvI9E1oj1q7WIOjOOrEdtK7Y",
	"3xTQF0qzicql8gNGs3eJZQu2Pj9Xmit5IVYxNbyIF+ZKcwuM9CjODv+sohlExqJg1vzbDXFFYBpQGPlf",
	"UZlIhu2EIulDMVwcALGdzw11T9zfdcclQ4ppNrUGX6H4tc2kiuQSQrQRt+exhCli07o3XyrNS4naIl5S",
	"VWQTxWrs4E447fIh2OmMTLMmRUU0s8QfiKwM/7ByaX46hQtuIrvqbeB2mVnNAhPkOs8lCCwinnQyDkqI",
	"l5PIpRlS9MpaqSJ6AGM4hRPowYgd5v3S/RxaC2TMkieaKZPsD3+DvkgvFsM5T+ixS/RA3KTfuxnJIyHd",
	"Z9OdaTwhF06QBQm5ShVpKlKaFlHUPUS+12zHjp3FTN/J9NyF/8AA0QPapX+BAT2gh9CnXRjQQ7GTR+ow",
	"vPFOhB7S56hSRTBE0BOaYiriydlnbA04Y6/C+YYhnwMnMEZlecoBhnAayzD7q9On0GP+WtnmoA/hycY1",
	"JmXEI/ILTW6H+ISPnsEfpptZltFM9F8TPNPVPE/pdjxPkKrBLMLdmy/dK99fny8vLtxffPDpn67NN7kk",
	"9/a9E/S5g+LWMqbHvGQyRJ44t+ytmDxxtxS33dfcrgbcRD3rPYMenLlCozsw5DMv4BLGvIYyoofceI8R",
	"jOGS22mP/gRDenw3vy16idzc5uilZ2axyEReRYD1SobK1spiuTMbciGyxYc3a8Y02w9unFCwbzCbSoOo",
	"9U2G0PYDfH1WHFs8IyM+hj6M4R2Mk0GphyfmJS0c3amWw3vAa776IJGOHzIT7tMjUdBkFs3k+yDeZAjn",
	"LIDLK6vPZd5mSgrk5hdYlOCiB47qF7EHnDK/c8Hd0LHgDswvHcA5DJBfPtxVmu00OuUPCuhUQ9F1w0Ge",
	"T0KGjoQMqFIVqtCNh4quaqp7o4rKRQ85gWFOn3bh0q2fcDfKyOFQUCOmqyzRYjXOQDrdQOKSi1xI8atj",
	"w5MHaTri2UBXUGcpVDyOefr0Q3tLj+A8UQqSMbKL7I+I1G3DJWT39qvZvIrsORnkGMjZ0WxX09dHYeEX",
	"6NGntEv/HBjRiQh2fokLLpk5Q5/hGrmhTGJ/9DgZNZNDXSbLiOoIzthrHifTnAjXNYITJiMbwocJrjsQ",
	"v+NNFRmR1fby19tEEkkfE0ckuGeND24+fCOaQCn7xdwgbtYiSe+NcPpyIeHya6GMdmzt30USTXhTaXxD",
	"dNWbIhLXsSkPQtkaFt87tdygElqSgekNDwcnLu/h9E5ca9gv3nUSh8gLDg1hasfswvKOY+Cdx5W430rg",
	"gnYLqFIt+DvQLruA8QtV+L45CMFBCB3CQdG0ivv8RDoTIVGxKtYKT2eEeoE29kWHjKk4O0GDjDl1e0zt",
	"SnjLd1Re84P0sJKnw93LR0i/ZaJyYEj8yAXtss/IOnnPyxb3XROYjAAvLSnarHIh4SqtUoVE59ZLzmbc",
	"xAA9ZAYWiuXc1ob0R/HFsoatptbSHBzeM5zHXSjL2ihuEpHR8mteXIYcgOCWt57Sep2fzEmCIE/Hjfym",
	"wDTvmPzOLBjbQcEwE7teYTEBWgkVeMZkFCGWXWCZEH3+qIfuVL94uLCw8NndFKRtWUZLDrSMyn8K4kcw",
	"oD9dRQjHuA4R/s2oDn1OD90GyXigSbU2v8skECF/YTEhxr9gDJf3VlN6jIRgXbjgyHzGY96Q/ozmS3d/",
	"I74ggk6Z0YXOQZgd46S5ucUresibXfOvgOgB4lcQdnW7kOo9xSIZ/SoqqpqdqFknSmtJVWdJzvhV5Y1I",
	"7VEElhCjmw+XAxfxUlNrEMwwljWpHJ30ubHJOWSYW5rKnugWyE0X1/1b1zUXdrzmjg+tEp9uZ2RgPFlz",
	"KCpPEuRlpKoSLvZ4sbE0W0El2n8cXFD9777Bskr8665aYolcDbvctrvMT/IVvC79CxiiO4EC6Qt6WIQx",
	"vHWTW+f0WGQupMkcGMD7cDaXnWDEIwSt7JMdQ9AYP4t/kAIzG5dTt5XcSpZV8lcAC9Gm/3Kox38+N/wS",
	"f38gQ+A/YQCntCtCBzttxMldD854qOiL6ykMb5+Hvsyupyaj4N8jcg+9OCgspE8PYEB/TBoGLynGqolD",
	"efKHZ3SKtMv9z7mb4IkR2WjgTJiJS1/TWCwb/5g4SQIrU2UwpBj9W50rUpmPKPZK7Tlf6I2h6BW8pX+F",
	"AYNFPIP28SNaXMW60WRiDj+fgkDuXBgExdU0C4js9m8/9kdOi8fw32jNjsZwyUhsf6MVp1o8YZivOn+L",
	"/crynrioMLlKTG/gkt0KYAxnqFL9RDjDtL+TmwDOSvUTelRA8I6hObMmlKuk4AGYIzECYJs4K/aS34qY",
	"zjX41LXQ6BnYRsihbSlNm+THyJUbTFMPOqvL8Qb4id8OnlCBzGVPdPUZqvJ2mtRBnfPu8CpEbl+IIg+8",
	"T0XmbyjT9qu40rsf5/KQH+AcevAOhTjQyO08GWb98WvC0Dr+s30vnyKiCAvs7gMxOPQgUoQKPf89UZrO",
	"Du7UOv8NAAD//x+IdMduPAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
